### ISSUE TITLE
Centos 6.6 python 2.6.6 error

### ISSUE THREAD

**Issue by vootbd** [miguelgrinberg/Flask-SocketIO-Chat#7]
getting this error on centos

Traceback (most recent call last):
  File "chat.py", line 2, in <module>
    from app import create_app, socketio
  File "/var/www/html/Flask-SocketIO-Chat-master/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
  File "/usr/lib/python2.6/site-packages/flask_socketio/__init__.py", line 481
    ssl_params = {k: kwargs[k] for k in kwargs if k in ssl_args}

Please help.
Thank you

**Comment by miguelgrinberg** [comment]
Python 2.6 is not supported, you need to upgrade to 2.7, 3.4, 3.5 or 3.6. Sorry.

**Comment by vootbd** [comment]
Thank you miguel, helped a lot.working fine on 3.4.
